### ISSUE TITLE
New form site verifications not output

### ISSUE THREAD

**Issue by jhabdas** [jekyll/jekyll-seo-tag#150]
#148 introduced additional verifications for Yandex, Bing and Alexa. The template updates were desk checked here with success: https://github.com/jhabdas/habd.as/commit/922b3da1fc8bcba27756854ad1bf557249cd5a64. But with the bump to Gem version `2.1.0` the new format does not output the verifications.

The previous backwards compat method of verification with Google still works as expected. I'm a baffled as to why the new format will not output. Thoughts @benbalter @pathawks? Sorry for the flub.

**Comment by pathawks** [comment]
`2.1.0` doesn't yet have the new verifications. We haven't yet published an updated version [since those changes were merged.](https://github.com/jekyll/jekyll-seo-tag/compare/v2.1.0...master)

If you want to always use bleeding edge features, you can setup your Gemfile to pull from GitHub rather than RubyGems. Otherwise, I expect we should publish a new version pretty soon :+1:

**Comment by jhabdas** [comment]
STGM. Thanks for the clarification, Mr @pathawks.
