### ISSUE TITLE
Consolidate `page.url` in template

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll-seo-tag#152]
Several places in the template call `{{ page.url | replace:'/index.html','/' | absolute_url }}`

Perhaps we could consolidate all of these into one assignment to `seo_page_url` so the filters are only called once instead of each time. This would DRY up the template semantically and may make generation a _tiny_ bit faster.

**Comment by dagoodma** [comment]
What about using `{{ site.url }}` instead of `{{ page.url }}`?  I'm having an issue with deploying to my production server from the dev environment because jekyll-seo-tag uses `{{ page.url }}`, and so I get bad links in my header:

```html
<link rel="canonical" href="http://localhost:4000/news/xxxxxxx/" />
<meta property="og:url" content="http://localhost:4000/news/xxxxxxx/" />
<meta property="og:site_name" content="xxxxxxx" />
<meta property="og:image" content="http://localhost:4000/%7B%22feature%22=%3E%22/assets/2017.03.03_xxxxxxx.png%22%7D" />
```

Where *localhost:4000* should be the `{{ site.url }}` so that it works in production.  Yes, I did set `JEKYLL_ENV=production` before running `jekyll build`.

The featured image bug seen above is a different issue entirely.  I'm going to fork this plugin and fix it myself for now.  I'll report back when I figure it out.

**Comment by dagoodma** [comment]
Oh nevermind.  That was my bad.  Maybe I didn't actually have the environment set.
