### ISSUE TITLE
broken author meta tag

### ISSUE THREAD

**Issue by gschueler** [jekyll/jekyll-seo-tag#186]
using github pages, previously this worked in our _config.yml

~~~{.yaml}
author:
  twitter: username
~~~

I think github pages upgraded to jekyll-seo-tag 2.2.0, and now that breaks the HTML page, by generating:

~~~{.html}
<meta name="author" content="{"twitter"=>"username"}" />
~~~

The readme specifies this as a valid config: https://github.com/jekyll/jekyll-seo-tag#author-information

changing the to `author: name` fixes the HTML issue

**Comment by pkra** [comment]
We encountered the same problem (though with `first_name` and `last_name` instead of the OP's `twitter`); also on github pages (but I can reproduce the issue locally as well). 

This results in artifacts in the compiled HTML (for lots of old content).

Might be due to https://github.com/jekyll/jekyll-seo-tag/pull/103.

**Comment by benbalter** [comment]
I *think* this should be fixed on `master` after https://github.com/jekyll/jekyll-seo-tag/pull/184.

**Comment by smashism** [comment]
Unfortunately I'm experiencing this issue on my site as well. This does not appear to be fixed.

**Comment by DirtyF** [comment]
@smashism with latest gem 2.2.1? Can you provide a link to a repository?

**Comment by mehmandarov** [comment]
Similar issue: https://github.com/jekyll/jekyll-seo-tag/issues/210

**Comment by benbalter** [comment]
#210 is a distinct issue. I'm going to call this closed on the latest version.
