### ISSUE TITLE
Using seo:type: Product incorrectly generates "headline" which google does not like

### ISSUE THREAD

**Issue by mlake** [jekyll/jekyll-seo-tag#81]

**Comment by pathawks** [comment]
Right now, the readme states:

> `type` - The type of things that the page represents. This must be a Schema.org type, and will probably usually be something like `BlogPosting`, `NewsArticle`, `Person`, `Organization`, etc.

Perhaps we could be more clear?

I don't think it is possible for the plugin to output different attributes depending on the `seo.type` of the page, so what is the next best solution?

**Comment by XhmikosR** [comment]
Why was this closed? Was it resolved?

**Comment by pathawks** [comment]
> Why was this closed?

It doesn't seem like any action is necessary. Readme addresses this already.

**Comment by XhmikosR** [comment]
How does it do that? Using the defaults for the plugin results in invalid
markup.

**Comment by dkmooers** [comment]
+1 for this. I'm trying to create a Product schema page and Google's structured markup validator doesn't like headline (because a Product should have a name, not a headline). I've successfully put name in there using YAML frontmatter, but IMO there should be a way to disable headline from showing in JSON-LD output using something like:

```
seo:
  headline: false
```
